name: Jobs
version: 0.1.0
main: com.webx.jobs.JobsPlugin
api-version: '1.20'
description: Player professions and job system

commands:
  job:
    description: Job system commands
    aliases: [jobs]
  work:
    description: Work and earn money
  job-info:
    description: View job information
  job-stats:
    description: View job statistics
