name: HorrorEngineX
version: 1.0.0
api-version: 1.13
main: com.webx.horrorenginex.HorrorEngineXPlugin
description: Horror engine plugin with atmospheric effects and scary events
authors:
  - miroslavsky
website: https://lxxv-project.com

commands:
  horrorenginex:
    description: HorrorEngineX plugin command
    usage: /horrorenginex <subcommand>
    aliases:
      - hex
      - horror
    permission: horrorenginex.admin

permissions:
  horrorenginex.admin:
    description: Admin permission for HorrorEngineX
    default: op
  horrorenginex.use:
    description: User permission for HorrorEngineX features
    default: true
  horrorenginex.bypass:
    description: Bypass horror effects
    default: false
