name: Randomizer
version: 1.0.0
main: com.webx.randomizer.RandomizerPlugin
api-version: 1.21
description: Randomizer plugin with teleport, items and number generation
authors:
  - LXXV
commands:
  randomizer:
    description: Shows randomizer menu with available commands
    usage: /randomizer
  randomtp:
    description: Teleport to random safe surface location
    usage: /randomtp
  randomitem:
    description: Get random wood or stick item (3 min cooldown)
    usage: /randomitem
  randomnumber:
    description: Generate random number between 1-1000
    usage: /randomnumber
