name: PvPEvents
version: 1.0.0
main: com.webx.pvpevents.PvPEventsPlugin
description: PvP event challenges
authors:
  - LXXV
commands:
  pvpevent:
    description: Control PvP events
    usage: /pvpevent <start|stop|type>
