name: Leveling
version: 1.0.0
main: com.webx.leveling.LevelingPlugin
description: Leveling system for players
authors:
  - LXXV
commands:
  level:
    description: Show your level
    usage: /level
