name: JumpQuests
version: 1.0.0
main: com.webx.jumpquests.JumpQuestsPlugin
description: Jump quest challenges
authors:
  - LXXV
commands:
  jumpquest:
    description: Jump quest commands
    usage: /jumpquest <list|join|checkpoint>
