name: FromDrop
version: 0.1.2
main: com.webx.fromdrop.FromDropPlugin
author: WebX
api-version: 1.20
commands:
  fromdrop:
    description: Reload FromDrop configuration
    usage: /fromdrop reload
    aliases: [fd]
    permission: fromdrop.admin
permissions:
  fromdrop.admin:
    default: op
    description: Allows reloading FromDrop
