name: Marketplace
version: 1.0.0
main: com.webx.marketplace.MarketplacePlugin
description: Player-to-player trading marketplace
authors:
  - LXXV
commands:
  marketplace:
    description: Open the marketplace
    usage: /marketplace
