name: Claims
version: 1.0.0
main: com.webx.claims.ClaimsPlugin
description: Land claiming system
authors:
  - LXXV
commands:
  claim:
    description: Manage land claims
    usage: /claim <create|delete|list>
