name: Quests
version: 0.1.0
main: com.webx.quests.QuestsPlugin
api-version: '1.20'
author: WebX
description: Quest system with objectives and rewards

commands:
  quests:
    description: Quest commands
    usage: /<command> <list|info|accept|abandon|complete>
    aliases: [q, quest]

permissions:
  quests.use:
    description: Use quest commands
    default: true
  quests.admin:
    description: Manage all quests
    default: op
