name: Statistics
version: 1.0.0
main: com.webx.statistics.StatisticsPlugin
description: Player statistics tracking
authors:
  - LXXV
commands:
  stats:
    description: View your statistics
    usage: /stats
