name: BackTP
version: 0.1.0
main: com.webx.backtp.BackTpPlugin
api-version: 1.20
author: WebX
description: Back to death location and TPA system

commands:
  back:
    description: Teleport to last death location
    usage: /back
  tpa:
    description: Send teleport request to player
    usage: /tpa <player>
  tpahere:
    description: Request player to teleport to you
    usage: /tpahere <player>
  tpaccept:
    description: Accept teleport request
    usage: /tpaccept
    aliases: [tpyes]
  tpdeny:
    description: Deny teleport request
    usage: /tpdeny
    aliases: [tpno]
